version: '2.1'

volumes:

  mozilla-iot-data:
  ssh-data:

services:

  mozilla-iot:
    build: ./mozilla-iot
    ports:
      - '80:8080'
      - '4443:4443'
    volumes:
      - 'mozilla-iot-data:/home/node/.mozilla-iot'
    volumes_from:
      - ssh:ro

  cloud9:
    build: ./cloud9
    ports:
      - '8080:8080'
    volumes:
      - 'mozilla-iot-data:/data:ro'
    volumes_from:
      - ssh

  ssh:
    build: ./ssh
    ports:
      - '22:22'
    volumes:
      - 'ssh-data:/root/.ssh'
    volumes_from:
      - cloud9

